from flask import Flask, render_template, request, jsonify, send_file
import requests
import pandas as pd
import json
import time
from pathlib import Path
import io

app = Flask(__name__)

# ── CONFIG ─────────────────────────────────────────────
INPUT_CSV = "trials_with_contacts.csv"
OUTPUT_JSON = "gregory_screened.json"
OUTPUT_MD = "gregory_patient_summary.md"

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3"
DISEASE_KEYWORD = "Amyotrophic Lateral Sclerosis"
OLLAMA_TIMEOUT = 120
# ───────────────────────────────────────────────────────

INCLUSION_PROMPT = """
You are a clinical trial nurse helping a patient understand if they might qualify for a study.

Below is the INCLUSION section of a clinical trial's eligibility criteria.
This describes who IS allowed to join.

---
{criteria}
---

Your task:
1. Extract the 3 most important requirements.
2. Rewrite each as a plain-English Yes/No question a patient can answer at home.
3. For each question, add a one-sentence note explaining WHY it matters.
4. Do NOT use medical jargon. Spell out acronyms. Use "you" language.

Format your response EXACTLY like this (no extra text before or after):
Q1: [Question]
WHY: [One sentence explanation]

Q2: [Question]
WHY: [One sentence explanation]

Q3: [Question]
WHY: [One sentence explanation]
""".strip()

EXCLUSION_PROMPT = """
You are a clinical trial nurse helping a patient understand what might DISQUALIFY them from a study.

Below is the EXCLUSION section of a clinical trial's eligibility criteria.
This describes who is NOT allowed to join.

---
{criteria}
---

Your task:
1. Identify the 2 most common or automatic disqualifiers.
2. Rewrite each as a plain-English Yes/No question. A "Yes" answer means they are disqualified.
3. Keep language gentle — patients may be distressed.
4. Do NOT use medical jargon.

Format your response EXACTLY like this (no extra text before or after):
STOP1: [Question — "Yes" means you may not qualify]
NOTE: [Brief, kind explanation]

STOP2: [Question — "Yes" means you may not qualify]
NOTE: [Brief, kind explanation]
""".strip()


def call_ollama(prompt: str) -> str:
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3,
            "num_predict": 400,
        }
    }

    try:
        resp = requests.post(OLLAMA_URL, json=payload, timeout=OLLAMA_TIMEOUT)
        if resp.status_code == 200:
            return resp.json().get("response", "").strip()
        return f"Error: Ollama returned status {resp.status_code}\n{resp.text}"
    except requests.exceptions.ConnectionError:
        return "Error: Cannot reach Ollama. Is it running? Try: ollama serve"
    except requests.exceptions.Timeout:
        return f"Error: Ollama timed out after {OLLAMA_TIMEOUT}s."
    except Exception as e:
        return f"Error: {e}"


def process_trial(trial: dict, dry_run: bool = False) -> dict:
    inclusion_raw = str(trial.get("inclusion", "")).strip()
    exclusion_raw = str(trial.get("exclusion", "")).strip()

    if inclusion_raw and inclusion_raw.lower() != "inclusion criteria:":
        inc_prompt = INCLUSION_PROMPT.format(criteria=inclusion_raw[:3000])
        inc_questions = "[DRY RUN — Ollama not called]" if dry_run else call_ollama(inc_prompt)
    else:
        inc_questions = "No inclusion criteria text available."

    if exclusion_raw and exclusion_raw.lower() != "exclusion criteria:":
        exc_prompt = EXCLUSION_PROMPT.format(criteria=exclusion_raw[:3000])
        exc_questions = "[DRY RUN — Ollama not called]" if dry_run else call_ollama(exc_prompt)
    else:
        exc_questions = "No exclusion criteria text available."

    return {
        "id": trial.get("id", ""),
        "title": trial.get("title", ""),
        "url": trial.get("url", ""),
        "email": trial.get("email", ""),
        "contact_name": trial.get("contact_name", ""),
        "email_source": trial.get("email_source", ""),
        "inclusion_questions": inc_questions,
        "exclusion_flags": exc_questions,
    }


def write_markdown(screened: list[dict], output_path: str):
    lines = [
        "# Project Gregory — Your Trial Screening Summary\n",
        "This document was generated by Gregory. It is not medical advice.  ",
        "Always confirm eligibility with the trial team before applying.\n",
        "---\n",
    ]

    for i, trial in enumerate(screened, 1):
        nct_id = trial["id"]
        title = trial["title"]
        url = trial.get("url", "")
        email = trial.get("email", "") or "See trial page"
        contact_name = trial.get("contact_name", "") or ""
        email_source = trial.get("email_source", "") or ""

        contact_line = email
        if contact_name:
            contact_line = f"{contact_name} — {email}"
        if email_source:
            contact_line += f" ({email_source})"

        lines += [
            f"## Trial {i}: {title}\n",
            f"*ID:* [{nct_id}]({url})  " if url else f"*ID:* {nct_id}  ",
            f"*Contact:* {contact_line}\n",
            "### ✅ To potentially qualify, answer YES to all of these:\n",
            trial["inclusion_questions"],
            "\n### 🛑 You may NOT qualify if you answer YES to any of these:\n",
            trial["exclusion_flags"],
            "\n---\n",
        ]

        if email and email != "See trial page" and "not listed" not in email.lower():
            lines += [
                "### 📧 Ready to apply?\n",
                f"Copy the text below and send it to *{email}*:\n",
                "",
                f"Subject: Enquiry about trial {nct_id} — {title}\n",
                "Dear Trial Coordinator,\n",
                "I am writing to enquire about eligibility for your trial listed on ClinicalTrials.gov "
                f"(NCT ID: {nct_id}).\n",
                "I have reviewed the eligibility criteria and believe I may qualify. "
                "Could you please advise on next steps?\n",
                "Thank you for your time.\n",
                "---\n",
            ]

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")


def load_trials(disease=None):
    csv_path = Path(INPUT_CSV)
    if not csv_path.exists():
        raise FileNotFoundError(f"Cannot find '{INPUT_CSV}'")

    df = pd.read_csv(csv_path)
    if disease and disease != DISEASE_KEYWORD:
        import subprocess
        subprocess.run(["py", "trials_prep.py", "--disease", disease], check=True)
        df = pd.read_csv(csv_path)

    required = ["id", "title", "url", "inclusion", "exclusion", "email"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns in CSV: {missing}. Found: {df.columns.tolist()}")

    return df.to_dict(orient="records")


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/health")
def health():
    try:
        resp = requests.get("http://localhost:11434/api/tags", timeout=5)
        if resp.status_code == 200:
            return jsonify({"ok": True, "message": "Ollama is running"})
        return jsonify({"ok": False, "message": f"Ollama returned {resp.status_code}"}), 500
    except Exception:
        return jsonify({"ok": False, "message": "Ollama is not running"}), 500


@app.route("/run", methods=["POST"])
def run():
    try:
        data = request.get_json(silent=True) or {}
        max_trials = data.get("max_trials", 5)
        disease = data.get("disease", DISEASE_KEYWORD)
        dry_run = data.get("dry_run", False)
        if max_trials is None:
            max_trials = 5

        max_trials = int(max_trials)
        if max_trials < 1:
            max_trials = 1

        trials = load_trials(disease)[:max_trials]

        screened = []
        for trial in trials:
            screened.append(process_trial(trial, dry_run=dry_run))
            time.sleep(0.3)

        Path(OUTPUT_JSON).write_text(json.dumps(screened, indent=2), encoding="utf-8")
        write_markdown(screened, OUTPUT_MD)

        return jsonify({
            "ok": True,
            "count": len(screened),
            "results": screened
        })

    except FileNotFoundError as e:
        return jsonify({"ok": False, "message": str(e)}), 400
    except ValueError as e:
        return jsonify({"ok": False, "message": str(e)}), 400
    except Exception as e:
        return jsonify({"ok": False, "message": str(e)}), 500


@app.route("/download")
def download():
    md_path = Path(OUTPUT_MD)
    if not md_path.exists():
        return "No markdown file generated yet.", 404

    return send_file(
        md_path,
        as_attachment=True,
        download_name="gregory_patient_summary.md"
    )


if __name__ == "__main__":
    app.run(debug=True)