import requests
import pandas as pd
import json
import time
import sys
sys.stdout.reconfigure(encoding='utf-8')
import argparse
from pathlib import Path

# ── CONFIGURATION ────────────────────────────────────────────────────────────
INPUT_CSV    = "trials_with_contacts.csv"      # ✅ this is your real file
OUTPUT_JSON  = "gregory_screened.json"
OUTPUT_MD    = "gregory_patient_summary.md"

OLLAMA_URL   = "http://localhost:11434/api/generate"
MODEL_NAME   = "llama3"
OLLAMA_TIMEOUT = 120

MAX_TRIALS   = None   # set to None to process everything
# ─────────────────────────────────────────────────────────────────────────────

INCLUSION_PROMPT = """
You are a clinical trial nurse helping a patient understand if they might qualify for a study.

Below is the INCLUSION section of a clinical trial's eligibility criteria.
This describes who IS allowed to join.

---
{criteria}
---

Your task:
1. Extract the 3 most important requirements.
2. Rewrite each as a plain-English Yes/No question a patient can answer at home.
3. For each question, add a one-sentence note explaining WHY it matters.
4. Do NOT use medical jargon. Spell out acronyms. Use "you" language.

Format your response EXACTLY like this (no extra text before or after):
Q1: [Question]
WHY: [One sentence explanation]

Q2: [Question]
WHY: [One sentence explanation]

Q3: [Question]
WHY: [One sentence explanation]
""".strip()

EXCLUSION_PROMPT = """
You are a clinical trial nurse helping a patient understand what might DISQUALIFY them from a study.

Below is the EXCLUSION section of a clinical trial's eligibility criteria.
This describes who is NOT allowed to join.

---
{criteria}
---

Your task:
1. Identify the 2 most common or automatic disqualifiers.
2. Rewrite each as a plain-English Yes/No question. A "Yes" answer means they are disqualified.
3. Keep language gentle — patients may be distressed.
4. Do NOT use medical jargon.

Format your response EXACTLY like this (no extra text before or after):
STOP1: [Question — "Yes" means you may not qualify]
NOTE: [Brief, kind explanation]

STOP2: [Question — "Yes" means you may not qualify]
NOTE: [Brief, kind explanation]
""".strip()


def call_ollama(prompt: str, dry_run: bool = False) -> str:
    if dry_run:
        return "[DRY RUN — Ollama not called]"

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3,
            "num_predict": 400,
        },
    }

    try:
        resp = requests.post(OLLAMA_URL, json=payload, timeout=OLLAMA_TIMEOUT)
        if resp.status_code == 200:
            return resp.json().get("response", "").strip()
        return f"Error: Ollama returned status {resp.status_code}\n{resp.text}"
    except requests.exceptions.ConnectionError:
        return "Error: Cannot reach Ollama. Is it running? Try: ollama serve"
    except requests.exceptions.Timeout:
        return f"Error: Ollama timed out after {OLLAMA_TIMEOUT}s. Try increasing timeout or using a smaller model."
    except Exception as e:
        return f"Error: {e}"


def process_trial(trial: dict, dry_run: bool) -> dict:
    inclusion_raw = str(trial.get("inclusion", "")).strip()
    exclusion_raw = str(trial.get("exclusion", "")).strip()

    # Inclusion
    if inclusion_raw and inclusion_raw.lower() != "inclusion criteria:":
        inc_prompt = INCLUSION_PROMPT.format(criteria=inclusion_raw[:3000])
        inc_questions = call_ollama(inc_prompt, dry_run)
    else:
        inc_questions = "No inclusion criteria text available."

    # Exclusion
    if exclusion_raw and exclusion_raw.lower() != "exclusion criteria:":
        exc_prompt = EXCLUSION_PROMPT.format(criteria=exclusion_raw[:3000])
        exc_questions = call_ollama(exc_prompt, dry_run)
    else:
        exc_questions = "No exclusion criteria text available."

        # Hallucination check
        hallucination_words = ["pregnant", "pregnancy", "breastfeeding", "allergy", "allergic"]
        if any(word in exc_questions.lower() for word in hallucination_words):
            exc_questions = "WARNING: Some disqualifiers may not apply to this trial. Please check the original criteria at the trial page.\n\n" + exc_questions

        return {
            "id": trial.get("id", ""),
            "title": trial.get("title", ""),
            "url": trial.get("url", ""),
            "email": trial.get("email", ""),
            "contact_name": trial.get("contact_name", ""),
            "email_source": trial.get("email_source", ""),
            "inclusion_questions": inc_questions,
            "exclusion_flags": exc_questions,
        }


def write_markdown(screened: list[dict], output_path: str):
    lines = [
        "# Project Gregory — Your Trial Screening Summary\n",
        "This document was generated by Gregory. It is not medical advice.  ",
        "Always confirm eligibility with the trial team before applying.\n",
        "---\n",
    ]

    for i, trial in enumerate([t for t in screened if t is not None], 1):
        nct_id = trial["id"]
        title = trial["title"]
        url = trial.get("url", "")
        email = trial.get("email", "") or "See trial page"
        contact_name = trial.get("contact_name", "") or ""
        email_source = trial.get("email_source", "") or ""

        contact_line = email
        if contact_name:
            contact_line = f"{contact_name} — {email}"
        if email_source:
            contact_line += f" ({email_source})"

        lines += [
            f"## Trial {i}: {title}\n",
            f"*ID:* [{nct_id}]({url})  " if url else f"*ID:* {nct_id}  ",
            f"*Contact:* {contact_line}\n",
            "### To potentially qualify, answer YES to all of these:\n",
            trial["inclusion_questions"],
            "\n###  You may NOT qualify if you answer YES to any of these:\n",
            trial["exclusion_flags"],
            "\n---\n",
        ]

        if email and email != "See trial page" and "not listed" not in email.lower():
            lines += [
                "###  Ready to apply?\n",
                f"Copy the text below and send it to *{email}*:\n",
                "",
                f"Subject: Enquiry about trial {nct_id} — {title}\n",
                "Dear Trial Coordinator,\n",
                "I am writing to enquire about eligibility for your trial listed on ClinicalTrials.gov "
                f"(NCT ID: {nct_id}).\n",
                "I have reviewed the eligibility criteria and believe I may qualify. "
                "Could you please advise on next steps?\n",
                "Thank you for your time.\n",
                "---\n",
            ]

    Path(output_path).write_text("\n\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Gregory — patient question generator (CSV-based)")
    parser.add_argument("--dry-run", action="store_true", help="Skip Ollama calls; useful for testing")
    parser.add_argument("--max", type=int, default=MAX_TRIALS, help="Max trials to process (None = all)")
    args = parser.parse_args()

    dry_run = args.dry_run
    max_count = args.max

    if not Path(INPUT_CSV).exists():
        print(f"Cannot find '{INPUT_CSV}'. Put it in the same folder as this script.")
        sys.exit(1)

    df = pd.read_csv(INPUT_CSV)

    # Ensure required columns exist (based on your CSV)
    required = ["id", "title", "url", "inclusion", "exclusion", "email"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"Missing columns in CSV: {missing}")
        print(f"   Found columns: {df.columns.tolist()}")
        sys.exit(1)

    trials = df.to_dict(orient="records")
    if max_count:
        trials = trials[:max_count]

    total = len(trials)
    print(f"Gregory: processing {total} trial{'s' if total != 1 else ''} "
          f"{'(DRY RUN)' if dry_run else 'via Llama 3'}...\n")

    if not dry_run:
        try:
            requests.get("http://localhost:11434/api/tags", timeout=5)
        except Exception:
            print("Ollama is not running. Start it with:  ollama serve")
            print("   Then ensure llama3 is available:      ollama pull llama3")
            sys.exit(1)

    screened = []
    for i, trial in enumerate(trials, 1):
        print(f"   [{i}/{total}] {trial.get('id','')} — {str(trial.get('title',''))[:60]}...")
        screened.append(process_trial(trial, dry_run))
        if not dry_run and i < total:
            time.sleep(0.5)

    Path(OUTPUT_JSON).write_text(json.dumps(screened, indent=2), encoding="utf-8")
    print(f"\nStructured JSON saved → '{OUTPUT_JSON}'")

    write_markdown(screened, OUTPUT_MD)
    print(f"Patient-ready Markdown saved → '{OUTPUT_MD}'")

    print("\nDone. Share 'gregory_patient_summary.md' with the patient.")
    print("   For best results, convert it to PDF before sending.")


if __name__ == "__main__":
    main()